Repository CMU-17313Q/fall23-nodebb-inshallah-a, pull requests merged in 2023-10, with the labels that each got.

#82 Adding frontend backend is urgent connection through composer.js file
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  src/topics/create.js
Labels: enhancement

#80 Created Urgent button front end and created a confirmation message for when the urgent button is clicked
  node_modules/nodebb-plugin-composer-default/static/less/composer.less
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  src/views/install/index.tpl
Labels: enhancement

#87 Resolving issue with frontend backend connection id incorrect
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  test/topics.js
Labels: bug fix

#81 Creating the urgent button next to the urgent posts
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
Labels: enhancement, tests pass

#89 Adding the topics urgent symbols on the list
  test/topics.js
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: enhancement, bug fix, tests pass

#102 Replaced line 14 in Dockerfile, based on instructions for Project 3 Deployment
  Dockerfile
Labels: deployment

#104 Completing second step p3 post-deployment (config_template.json, create_config.sh, Dockerfile) in root directory
  Dockerfile
  config_template.json
  create_config.sh
Labels: deployment

#105 Added the static tool called "hegel"
  .babelrc
  package.json
Labels: static tool

#106 Added the output of the documentation in terms of the static tool hegel
  documentation
Labels: static tool

#108 Adding fix the Professor said on slack for permissions relating `create_config.sh`
  create_config.sh
Labels: deployment

#109 Intended to trigger redeployment
  create_config.sh
Labels: deployment

#114 Added the flow tool in the package.json
  .babelrc
  package.json
  src/controllers/category.js
Labels: static tool

#115 Update documentation file
  documentation
Labels: static tool

#117 installed dynamic tool called Stryker Mutator
  package.json
Labels: Dynamic tool

#121 Line 12 of the Dockerfile was changed to account for package.json.docker
  Dockerfile
Labels: deployment

#125 Update test.yaml to include flow commands of init and running `npx flow`
  .github/workflows/flow.yaml
  package.json
  src/controllers/category.js
Labels: static tool

#126 Update documentation of hegel
  documentation
Labels: static tool
